"""added columns gender and dob

Revision ID: 1b0cb9c7c5a7
Revises: 2d086e7b1bd1
Create Date: 2024-11-20 19:13:48.172921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0cb9c7c5a7'
down_revision = '2d086e7b1bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dob')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
